# Docker

# Build and push an image to Azure Container Registry

# https://docs.microsoft.com/azure/devops/pipelines/languages/docker



trigger:

- master



resources:

- repo: self







  # Agent VM image name

  vmImageName: 'ubuntu-latest'







    - task: CopyFiles@2

      inputs:

        SourceFolder: '$(System.DefaultWorkingDirectory)'

        Contents: '**/*.yml'

        TargetFolder: '$(Build.ArtifactStagingDirectory)'





    - task: PublishBuildArtifacts@1

      inputs:

        PathtoPublish: '$(Build.ArtifactStagingDirectory)'

        ArtifactName: 'artifact'

        publishLocation: 'Container'



    - task: DownloadBuildArtifacts@1

      inputs:

        buildType: 'current'

        downloadType: 'single'

        artifactName: 'artifact'

        itemPattern: '**/*.yml'

        downloadPath: '$(System.ArtifactsDirectory)'



    - task: KubernetesManifest@0

      inputs:

        action: 'deploy'

        kubernetesServiceConnection: 'kubernetes1'

        namespace: 'default'

        manifests: '$(System.ArtifactsDirectory)/deploy.yml'

        containers: kausikisamadder19.azurecr.io/webapplication14:latest