apiVersion: apps/v1

kind: Deployment

metadata:

  name: sampleapp

spec:

  replicas: 1

  selector:

    matchLabels:

      name: sampleapp

  template:

    metadata:

      labels:

        name: sampleapp

    spec:

      nodeSelector:

        "beta.kubernetes.io/os": linux

      containers:

      - name: sampleapp

        image: docker pull kausikisamadder19.azurecr.io/webapplication14:latest

        ports:

        - containerPort: 80



---

apiVersion: v1

kind: Service

metadata:

  name: sampleapp

spec:

  type: LoadBalancer

  ports:

  - port: 80

  selector:

    name: sampleapp
